development:
  host: 'localhost'
  username: 'root'
  password: 'root'
  database: 'auth_server'
  adapter: mysql2
  socket: '/var/run/mysqld/mysqld.sock' 
  pool: 5
  timeout: 5000

production:
  host: 'localhost'
  username: 'root'
  password: 'root'
  database: 'auth_server'
  adapter: mysql2
  socket: '/var/run/mysqld/mysqld.sock' 
  pool: 5
  timeout: 5000
